version: "3.8"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    restart: always

  frontend_next:
    build:
      context: ./frontend_next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend_next:/app
    restart: always
