pipeline {
    agent any
    
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/AshwinK01/Capstone-2.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Navigate to frontend folder
                    dir('frontend') {
                        // Build the Docker image
                        sh 'docker build -t malware_classifier .'
                    }
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    // Stop any existing container
                    sh 'docker stop malware_classifier || true && docker rm malware_classifier || true'
                    
                    // Run the Docker container
                    sh 'docker run -d -p 3000:3000 --name malware_classifier malware_classifier'
                }
            }
        }
    }
}
