pipeline {
    agent any
    
    tools {
        nodejs 'NodeJS' // Specify the NodeJS installation configured in Jenkins
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/AshwinK01/Capstone-2.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                dir('Frontend') {
                    script {
                        // Use npm from the tools configuration
                        sh 'npm install'
                    }
                }
            }
        }
        
        stage('Build Project') {
            steps {
                dir('Frontend') {
                    sh 'npm run build'
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                dir('Frontend') {
                    sh 'docker build -t malware_classifier .'
                }
            }
        }
        
        stage('Run Docker Container') {
            steps {
                script {
                    sh '''
                        docker stop malware_classifier || true
                        docker rm malware_classifier || true
                        docker run -d -p 3000:3000 --name malware_classifier malware_classifier
                    '''
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline finished.'
            // Clean up workspace
            cleanWs()
        }
        failure {
            echo 'Pipeline failed!'
        }
        success {
            echo 'Pipeline succeeded!'
        }
    }
}
