services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend_next
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    restart: always
